// Who actually made the request.
//
// On 2026-09-04 an unauthenticated POST deleted an admin account and, by
// cascade, 186 units. The logs named 172.71.15.128 as the caller. That is a
// Cloudflare edge address, not a person -- and the reason it was the only thing
// on record is not that logging was too thin. It is that the host was throwing
// the real address away:
//
//   nginx sets  X-Real-IP: $remote_addr   which behind Cloudflare IS Cloudflare
//   am2_client_ip() reads X-Real-IP       and stops there
//   Apache's `combined` LogFormat uses %h  which is 127.0.0.1, the loopback peer
//
// The visitor's address arrives in CF-Connecting-IP. The fix is not to read
// that header in PHP: PHP cannot tell whether the request came through
// Cloudflare at all, so trusting it there would let anyone reaching the origin
// name themselves whatever they like. nginx can tell, because it sees the peer
// address, and http_realip_module exists for exactly this -- it rewrites
// $remote_addr only when the peer is inside Cloudflare's published ranges.
//
// Do that and everything downstream becomes correct without changing: X-Real-IP
// carries the visitor, am2_client_ip() reads the visitor, the access log records
// the visitor.
import test, { describe } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const read = (p) => readFileSync(join(ROOT, p), 'utf8');
const SNIPPET = 'infra/nginx/am2-cloudflare-realip.conf';

describe('client attribution', () => {
    test('nginx is told which peers may speak for someone else', () => {
        assert.ok(existsSync(join(ROOT, SNIPPET)), `${SNIPPET} does not exist`);
        const s = read(SNIPPET);

        assert.match(s, /real_ip_header\s+CF-Connecting-IP\s*;/,
            'nginx does not read the visitor address Cloudflare sends');

        // The guard, and the whole reason this is safe: $remote_addr is
        // rewritten only for peers inside these ranges. A request that reaches
        // the origin another way keeps its real peer address and cannot claim
        // to be anyone.
        const v4 = (s.match(/^\s*set_real_ip_from\s+[0-9.]+\/\d+\s*;/gm) || []).length;
        const v6 = (s.match(/^\s*set_real_ip_from\s+[0-9a-f:]+\/\d+\s*;/gim) || []).length;
        // Thresholds, not exact counts. Cloudflare publishes a new range from
        // time to time and pinning the number would turn a legitimate change
        // into a red build -- the kind of alarm people learn to ignore. This
        // catches gross truncation, which is the failure that matters: a
        // half-written list stops nginx trusting most of Cloudflare and every
        // address silently becomes the edge again.
        assert.ok(v4 >= 10, `expected Cloudflare's IPv4 ranges, found ${v4}`);
        assert.ok(v6 >= 5, `expected Cloudflare's IPv6 ranges, found ${v6}`);
        // Provenance, because the content itself is guarded by the generator
        // rather than by this test. A hand-edited file loses this line.
        assert.match(s, /Generated by infra\/scripts\/refresh-cloudflare-ranges\.sh/,
            'the range list was hand-edited; it must come from the refresher');
    });

    test('every public server block trusts the same list', () => {
        // Missing it on one vhost is worse than missing it everywhere: the logs
        // then disagree about what an address means, and nobody notices until
        // they are being read in an incident.
        for (const f of ['infra/nginx/am2-webadmin.conf',
                         'infra/nginx/am2-webadmin-staging.conf',
                         'infra/nginx/am2-api.conf']) {
            assert.match(read(f), /include\s+snippets\/am2-cloudflare-realip\.conf\s*;/,
                `${f} does not resolve the visitor address`);
        }
    });

    test('PHP does not trust a header it cannot verify', () => {
        // The tempting shortcut, and the wrong one. am2_client_ip() runs behind
        // a loopback Apache that anything on the host can reach directly, so a
        // header read there proves nothing about who sent it.
        const config = read('WebAdmin/config.php');
        const start = config.indexOf('function am2_client_ip(');
        const body = config.slice(start, config.indexOf('\n}', start));
        assert.doesNotMatch(body, /CF_CONNECTING_IP|CF-Connecting-IP/i,
            'the panel trusts a forwarded header directly instead of letting nginx validate it');
        assert.match(body, /HTTP_X_REAL_IP/,
            'the panel no longer reads the address nginx resolved');
    });

    test('the access log records the visitor, not the loopback', () => {
        // %h is the peer, and the peer is always 127.0.0.1 here because nginx
        // is in front. The address nginx resolved has to be logged explicitly
        // or the access log stays useless for attribution.
        for (const f of ['infra/apache/am2-webadmin-internal.conf',
                         'infra/apache/am2-webadmin-staging.conf']) {
            assert.match(read(f), /LogFormat\s+"[^"]*%\{X-Real-IP\}i/,
                `${f} logs the loopback peer and nothing else`);
        }
    });

    test('the ranges can be refreshed without anyone remembering the URL', () => {
        const script = 'infra/scripts/refresh-cloudflare-ranges.sh';
        assert.ok(existsSync(join(ROOT, script)), `${script} does not exist`);
        const s = read(script);
        assert.match(s, /cloudflare\.com\/ips-v4/);
        assert.match(s, /cloudflare\.com\/ips-v6/);
        // A truncated fetch that overwrites the list would silently stop nginx
        // trusting Cloudflare, and every address in the logs would become the
        // edge again -- the exact failure this work exists to end.
        assert.match(s, /v4|count|wc -l/,
            'the refresh does not check it received a plausible list');
    });
});
