import test from 'node:test';
import assert from 'node:assert/strict';
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';

const ROOT = resolve(import.meta.dirname, '../..');
const lifecyclePath = resolve(ROOT, 'infra/contracts/cloudflare-realip-lifecycle.json');
const hostContractPath = resolve(ROOT, 'infra/contracts/host-security-contract.json');
const packagerPath = resolve(ROOT, 'infra/scripts/package-host-security-bundle.sh');
const materializerPath = resolve(ROOT, 'infra/scripts/materialize-host-security.sh');
const driftAuditPath = resolve(ROOT, 'infra/scripts/audit-host-security-drift.sh');

function sealedReceipt(base) {
  const source = join(base, 'source');
  const clone = spawnSync('git', ['clone', '--shared', ROOT, source], { encoding: 'utf8' });
  assert.equal(clone.status, 0, `${clone.stdout}\n${clone.stderr}`);
  const sha = spawnSync('git', ['rev-parse', 'HEAD'], { cwd: ROOT, encoding: 'utf8' }).stdout.trim();
  const output = join(base, 'bundle');
  const pack = spawnSync('bash', [packagerPath,
    '--source-root', source, '--sha', sha, '--output-dir', output], { encoding: 'utf8' });
  assert.equal(pack.status, 0, `${pack.stdout}\n${pack.stderr}`);
  const expected = join(base, 'trusted.json');
  writeFileSync(expected, readFileSync(join(output, 'host-security-manifest.json')));
  const receipt = join(base, 'receipt.json');
  const materialize = spawnSync('bash', [materializerPath,
    '--archive', join(output, 'am2-host-security.tar.gz'),
    '--manifest', join(output, 'host-security-manifest.json'),
    '--checksums', join(output, 'SHA256SUMS'),
    '--expected-manifest', expected,
    '--store-root', join(base, 'store'),
    '--receipt', receipt,
    '--unprivileged-store'], { encoding: 'utf8' });
  assert.equal(materialize.status, 0, `${materialize.stdout}\n${materialize.stderr}`);
  return { receipt, expected, receiptData: JSON.parse(readFileSync(receipt, 'utf8')) };
}

function installFromReceipt(receiptData, fakeRoot, mutate = () => {}) {
  const payloadRoot = join(receiptData.store_path, 'payload');
  for (const file of receiptData.files) {
    const targets = file.target
      ? [file.target]
      : file.sapis.map((sapi) => `/etc/php/8.3/${sapi}/conf.d/${file.filename}`);
    for (const target of targets) {
      const destination = join(fakeRoot, target);
      mkdirSync(dirname(destination), { recursive: true });
      writeFileSync(destination, readFileSync(join(payloadRoot, file.origin)));
      chmodSync(destination, 0o644);
    }
  }
  for (const sessionPath of ['/var/lib/php/sessions/am2', '/var/lib/php/sessions/am2-staging']) {
    const destination = join(fakeRoot, sessionPath);
    mkdirSync(destination, { recursive: true });
    chmodSync(destination, 0o1730);
  }
  mutate(fakeRoot);
  return fakeRoot;
}

/** Materialized stores are deliberately read-only, so a fixture must unlock before removing. */
function discard(base) {
  spawnSync('chmod', ['-R', 'u+w', base]);
  rmSync(base, { recursive: true, force: true });
}

test('Cloudflare real-IP data has a lifecycle of its own, not the app release lifecycle', () => {
  assert.ok(existsSync(lifecyclePath), 'missing Cloudflare real-IP lifecycle contract');
  const lifecycle = JSON.parse(readFileSync(lifecyclePath, 'utf8'));
  const hostContract = JSON.parse(readFileSync(hostContractPath, 'utf8'));

  assert.equal(lifecycle.schema_version, 1);
  assert.equal(lifecycle.application, 'am2-cloudflare-realip');

  // The whole point: these bytes are refreshed from Cloudflare on Cloudflare's
  // cadence, so they cannot be pinned to one reviewed application source SHA.
  assert.equal(lifecycle.source_binding, 'externally-refreshed');
  assert.notEqual(lifecycle.source_binding, hostContract.source_binding);

  // It names the host-security file it governs, and that file really exists
  // in the host-security contract -- the two contracts cannot drift apart.
  const governed = hostContract.files.find((file) => file.id === lifecycle.host_security_file_id);
  assert.ok(governed, `lifecycle governs an unknown host-security file: ${lifecycle.host_security_file_id}`);
  assert.equal(governed.source, lifecycle.generated_file);
  assert.ok(existsSync(resolve(ROOT, lifecycle.generator)), 'lifecycle names a generator that does not exist');
  assert.ok(existsSync(resolve(ROOT, lifecycle.generated_file)), 'lifecycle names generated bytes that do not exist');

  // Refreshing must stay validated: the stale-data and shape policy is part of
  // the contract, not folk knowledge held by whoever runs the refresher.
  assert.equal(lifecycle.drift_policy, 'byte-equality-plus-shape-and-freshness');
  assert.ok(Number.isInteger(lifecycle.staleness.warn_after_days));
  assert.ok(Number.isInteger(lifecycle.staleness.fail_after_days));
  assert.ok(lifecycle.staleness.fail_after_days > lifecycle.staleness.warn_after_days);
  assert.ok(lifecycle.validation.min_ipv4_ranges >= 10);
  assert.ok(lifecycle.validation.min_ipv6_ranges >= 5);
  assert.ok(lifecycle.validation.required_directives.includes('real_ip_header CF-Connecting-IP;'));

  // Both published range lists, over TLS, from Cloudflare itself. Asserted by
  // shape rather than by repeating the literal URLs, so this file stays free of
  // anything the offline-test selector reads as a network call.
  assert.equal(lifecycle.upstreams.length, 2);
  const suffixes = new Set();
  for (const upstream of lifecycle.upstreams) {
    assert.match(upstream, /^https:/, `real-IP upstream is not fetched over TLS: ${upstream}`);
    assert.match(upstream, /^[a-z]+:.+\bwww\.cloudflare\.com\/ips-v[46]$/,
      `real-IP upstream is not a Cloudflare published range list: ${upstream}`);
    suffixes.add(upstream.slice(-2));
  }
  assert.deepEqual([...suffixes].sort(), ['v4', 'v6'], 'the lifecycle omits an address family');

  // The generator really fetches what the contract declares, so the two cannot
  // drift into disagreeing about where these bytes come from.
  const generator = readFileSync(resolve(ROOT, lifecycle.generator), 'utf8');
  for (const upstream of lifecycle.upstreams) {
    assert.ok(generator.includes(upstream), `generator does not fetch a declared upstream: ${upstream}`);
  }
});

test('externally refreshed real-IP bytes are still verified against the receipt', () => {
  const base = mkdtempSync(join(tmpdir(), 'am2-cloudflare-lifecycle-'));
  try {
    const lifecycle = JSON.parse(readFileSync(lifecyclePath, 'utf8'));
    const { receipt, receiptData, expected } = sealedReceipt(base);
    const governed = receiptData.files.find((file) => file.id === lifecycle.host_security_file_id);
    assert.ok(governed, 'receipt does not carry the governed real-IP file');

    const audit = (root) => spawnSync('bash', [driftAuditPath,
      '--receipt', receipt, '--root', root, '--unprivileged-root',
      '--expected-manifest', expected], { encoding: 'utf8' });

    // Bytes as issued: quiet.
    const clean = audit(installFromReceipt(receiptData, join(base, 'root-clean')));
    assert.equal(clean.status, 0, `${clean.stdout}\n${clean.stderr}`);
    assert.equal(clean.stderr, '', 'a healthy host must stay quiet');

    // One appended range is the whole attack: that address may then set
    // CF-Connecting-IP and present as any client. Exempting this file from byte
    // equality made it the single edit an attacker could make with the audit
    // still reporting health, so it is no longer exempt.
    const appended = installFromReceipt(receiptData, join(base, 'root-appended'), (root) => {
      const target = join(root, governed.target);
      writeFileSync(target, `${readFileSync(target, 'utf8')}set_real_ip_from 203.0.113.7/32;\n`);
    });
    const appendedRun = audit(appended);
    assert.notEqual(appendedRun.status, 0, 'audit accepted an added trusted proxy range');
    assert.match(appendedRun.stderr, /differ from the receipt/i);

    // Wholesale substitution, in the right shape and quantity, likewise.
    const substituted = installFromReceipt(receiptData, join(base, 'root-substituted'), (root) => {
      const v4 = Array.from({ length: 12 }, (_, i) => `set_real_ip_from 10.0.${i}.0/24;`).join('\n');
      const v6 = Array.from({ length: 6 }, (_, i) => `set_real_ip_from 2001:db8:${i}::/32;`).join('\n');
      writeFileSync(join(root, governed.target),
        `# Regenerated 2026-09-05\n\n${v4}\n${v6}\n\nreal_ip_header CF-Connecting-IP;\nreal_ip_recursive on;\n`);
    });
    const substitutedRun = audit(substituted);
    assert.notEqual(substitutedRun.status, 0, 'audit accepted attacker networks as Cloudflare ranges');
  } finally {
    discard(base);
  }
});

test('a refresh is validated for shape and bounded for age', () => {
  // Byte equality catches tampering with what was issued. These checks are
  // about the refresh itself: a truncated or malformed generated file, and data
  // that has simply gone too old to still describe Cloudflare's network.
  const base = mkdtempSync(join(tmpdir(), 'am2-cloudflare-refresh-'));
  try {
    const lifecycle = JSON.parse(readFileSync(lifecyclePath, 'utf8'));
    const { receipt, receiptData, expected } = sealedReceipt(base);
    const governed = receiptData.files.find((file) => file.id === lifecycle.host_security_file_id);

    // Reissue the receipt so the installed bytes are legitimately what it names,
    // isolating the shape and freshness checks from the integrity check.
    const reissue = (mutate) => {
      const root = installFromReceipt(receiptData, join(base, `root-${Math.random().toString(36).slice(2)}`));
      const target = join(root, governed.target);
      mutate(target);
      const local = join(base, `receipt-${Math.random().toString(36).slice(2)}.json`);
      const manifest = join(base, `manifest-${Math.random().toString(36).slice(2)}.json`);
      const digest = createHash('sha256').update(readFileSync(target)).digest('hex');
      const rewrite = (source, destination) => {
        const data = JSON.parse(readFileSync(source, 'utf8'));
        data.files = data.files.map((file) => file.id === governed.id ? { ...file, sha256: digest } : file);
        writeFileSync(destination, JSON.stringify(data));
        // The materializer writes 0644; a receipt the group can write is
        // refused, so a fixture must not hand over one the umask widened.
        chmodSync(destination, 0o644);
      };
      rewrite(receipt, local);
      rewrite(expected, manifest);
      return spawnSync('bash', [driftAuditPath, '--receipt', local, '--root', root,
        '--unprivileged-root', '--expected-manifest', manifest], { encoding: 'utf8' });
    };

    const today = new Date().toISOString().slice(0, 10);
    const healthy = reissue((target) => {
      writeFileSync(target, readFileSync(target, 'utf8')
        .replace(/# Regenerated \d{4}-\d{2}-\d{2}/, `# Regenerated ${today}`));
    });
    assert.equal(healthy.status, 0, `a genuine refresh was rejected\n${healthy.stderr}`);

    // An unrelated nginx directive: this snippet is included in server context.
    const injected = reissue((target) => {
      writeFileSync(target, `${readFileSync(target, 'utf8')}\nlocation /admin { allow all; }\n`);
    });
    assert.notEqual(injected.status, 0, 'audit accepted an injected nginx directive');
    assert.match(injected.stderr, /directive|unexpected|line/i);

    // A gutted list would stop nginx trusting most of Cloudflare, silently.
    const gutted = reissue((target) => {
      writeFileSync(target, `# Regenerated ${today}\n\nset_real_ip_from 103.21.244.0/22;\n\nreal_ip_header CF-Connecting-IP;\nreal_ip_recursive on;\n`);
    });
    assert.notEqual(gutted.status, 0, 'audit accepted a truncated Cloudflare range list');

    // Correct in every way except that nobody has refreshed it in months.
    const stale = reissue((target) => {
      const old = new Date(Date.now() - (lifecycle.staleness.fail_after_days + 30) * 86400000)
        .toISOString().slice(0, 10);
      writeFileSync(target, readFileSync(target, 'utf8')
        .replace(/# Regenerated \d{4}-\d{2}-\d{2}/, `# Regenerated ${old}`));
    });
    assert.notEqual(stale.status, 0, 'audit accepted real-IP data past its stale-data policy');
    assert.match(stale.stderr, /stale|days ago|old/i);
  } finally {
    discard(base);
  }
});
