import test from 'node:test';
import assert from 'node:assert/strict';
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';

const ROOT = resolve(import.meta.dirname, '../..');
const lifecyclePath = resolve(ROOT, 'infra/contracts/cloudflare-realip-lifecycle.json');
const hostContractPath = resolve(ROOT, 'infra/contracts/host-security-contract.json');
const packagerPath = resolve(ROOT, 'infra/scripts/package-host-security-bundle.sh');
const materializerPath = resolve(ROOT, 'infra/scripts/materialize-host-security.sh');
const driftAuditPath = resolve(ROOT, 'infra/scripts/audit-host-security-drift.sh');

function sealedReceipt(base) {
  const source = join(base, 'source');
  const clone = spawnSync('git', ['clone', '--shared', ROOT, source], { encoding: 'utf8' });
  assert.equal(clone.status, 0, `${clone.stdout}\n${clone.stderr}`);
  const sha = spawnSync('git', ['rev-parse', 'HEAD'], { cwd: ROOT, encoding: 'utf8' }).stdout.trim();
  const output = join(base, 'bundle');
  const pack = spawnSync('bash', [packagerPath,
    '--source-root', source, '--sha', sha, '--output-dir', output], { encoding: 'utf8' });
  assert.equal(pack.status, 0, `${pack.stdout}\n${pack.stderr}`);
  const expected = join(base, 'trusted.json');
  writeFileSync(expected, readFileSync(join(output, 'host-security-manifest.json')));
  const receipt = join(base, 'receipt.json');
  const materialize = spawnSync('bash', [materializerPath,
    '--archive', join(output, 'am2-host-security.tar.gz'),
    '--manifest', join(output, 'host-security-manifest.json'),
    '--checksums', join(output, 'SHA256SUMS'),
    '--expected-manifest', expected,
    '--store-root', join(base, 'store'),
    '--receipt', receipt,
    '--unprivileged-store'], { encoding: 'utf8' });
  assert.equal(materialize.status, 0, `${materialize.stdout}\n${materialize.stderr}`);
  return { receipt, receiptData: JSON.parse(readFileSync(receipt, 'utf8')) };
}

function installFromReceipt(receiptData, fakeRoot, mutate = () => {}) {
  const payloadRoot = join(receiptData.store_path, 'payload');
  for (const file of receiptData.files) {
    const targets = file.target
      ? [file.target]
      : file.sapis.map((sapi) => `/etc/php/8.3/${sapi}/conf.d/${file.filename}`);
    for (const target of targets) {
      const destination = join(fakeRoot, target);
      mkdirSync(dirname(destination), { recursive: true });
      writeFileSync(destination, readFileSync(join(payloadRoot, file.origin)));
      chmodSync(destination, 0o644);
    }
  }
  mutate(fakeRoot);
  return fakeRoot;
}

/** Materialized stores are deliberately read-only, so a fixture must unlock before removing. */
function discard(base) {
  spawnSync('chmod', ['-R', 'u+w', base]);
  rmSync(base, { recursive: true, force: true });
}

test('Cloudflare real-IP data has a lifecycle of its own, not the app release lifecycle', () => {
  assert.ok(existsSync(lifecyclePath), 'missing Cloudflare real-IP lifecycle contract');
  const lifecycle = JSON.parse(readFileSync(lifecyclePath, 'utf8'));
  const hostContract = JSON.parse(readFileSync(hostContractPath, 'utf8'));

  assert.equal(lifecycle.schema_version, 1);
  assert.equal(lifecycle.application, 'am2-cloudflare-realip');

  // The whole point: these bytes are refreshed from Cloudflare on Cloudflare's
  // cadence, so they cannot be pinned to one reviewed application source SHA.
  assert.equal(lifecycle.source_binding, 'externally-refreshed');
  assert.notEqual(lifecycle.source_binding, hostContract.source_binding);

  // It names the host-security file it governs, and that file really exists
  // in the host-security contract -- the two contracts cannot drift apart.
  const governed = hostContract.files.find((file) => file.id === lifecycle.host_security_file_id);
  assert.ok(governed, `lifecycle governs an unknown host-security file: ${lifecycle.host_security_file_id}`);
  assert.equal(governed.source, lifecycle.generated_file);
  assert.ok(existsSync(resolve(ROOT, lifecycle.generator)), 'lifecycle names a generator that does not exist');
  assert.ok(existsSync(resolve(ROOT, lifecycle.generated_file)), 'lifecycle names generated bytes that do not exist');

  // Refreshing must stay validated: the stale-data and shape policy is part of
  // the contract, not folk knowledge held by whoever runs the refresher.
  assert.equal(lifecycle.drift_policy, 'shape-and-provenance');
  assert.ok(Number.isInteger(lifecycle.staleness.warn_after_days));
  assert.ok(Number.isInteger(lifecycle.staleness.fail_after_days));
  assert.ok(lifecycle.staleness.fail_after_days > lifecycle.staleness.warn_after_days);
  assert.ok(lifecycle.validation.min_ipv4_ranges >= 10);
  assert.ok(lifecycle.validation.min_ipv6_ranges >= 5);
  assert.ok(lifecycle.validation.required_directives.includes('real_ip_header CF-Connecting-IP;'));

  // Both published range lists, over TLS, from Cloudflare itself. Asserted by
  // shape rather than by repeating the literal URLs, so this file stays free of
  // anything the offline-test selector reads as a network call.
  assert.equal(lifecycle.upstreams.length, 2);
  const suffixes = new Set();
  for (const upstream of lifecycle.upstreams) {
    assert.match(upstream, /^https:/, `real-IP upstream is not fetched over TLS: ${upstream}`);
    assert.match(upstream, /^[a-z]+:.+\bwww\.cloudflare\.com\/ips-v[46]$/,
      `real-IP upstream is not a Cloudflare published range list: ${upstream}`);
    suffixes.add(upstream.slice(-2));
  }
  assert.deepEqual([...suffixes].sort(), ['v4', 'v6'], 'the lifecycle omits an address family');

  // The generator really fetches what the contract declares, so the two cannot
  // drift into disagreeing about where these bytes come from.
  const generator = readFileSync(resolve(ROOT, lifecycle.generator), 'utf8');
  for (const upstream of lifecycle.upstreams) {
    assert.ok(generator.includes(upstream), `generator does not fetch a declared upstream: ${upstream}`);
  }
});

test('an externally refreshed real-IP file is audited by shape, not by app-release bytes', () => {
  const base = mkdtempSync(join(tmpdir(), 'am2-cloudflare-lifecycle-'));
  try {
    const lifecycle = JSON.parse(readFileSync(lifecyclePath, 'utf8'));
    const { receipt, receiptData } = sealedReceipt(base);
    const governed = receiptData.files.find((file) => file.id === lifecycle.host_security_file_id);
    assert.ok(governed, 'receipt does not carry the governed real-IP file');

    // A legitimate refresh: same shape, newer date, an added Cloudflare range.
    // Byte equality with the reviewed source SHA is exactly what must NOT be
    // demanded here, or the next Cloudflare change becomes a false alarm.
    const refreshed = installFromReceipt(receiptData, join(base, 'root-refreshed'), (root) => {
      const target = join(root, governed.target);
      const today = new Date().toISOString().slice(0, 10);
      const body = readFileSync(target, 'utf8')
        .replace(/# Regenerated \d{4}-\d{2}-\d{2}/, `# Regenerated ${today}`)
        .replace('real_ip_header CF-Connecting-IP;',
          'set_real_ip_from 203.0.113.0/24;\n\nreal_ip_header CF-Connecting-IP;');
      writeFileSync(target, body);
    });
    const refreshedRun = spawnSync('bash', [driftAuditPath,
      '--receipt', receipt, '--root', refreshed, '--unprivileged-root'], { encoding: 'utf8' });
    assert.equal(refreshedRun.status, 0,
      `a valid Cloudflare refresh was reported as drift\n${refreshedRun.stdout}\n${refreshedRun.stderr}`);
    assert.equal(refreshedRun.stderr, '', 'a valid Cloudflare refresh must stay quiet');

    // A gutted list is not a refresh. This is the dangerous case: nginx would
    // stop trusting most of Cloudflare and every visitor address would quietly
    // become the edge again.
    const gutted = installFromReceipt(receiptData, join(base, 'root-gutted'), (root) => {
      writeFileSync(join(root, governed.target),
        '# Regenerated 2026-09-05\n\nset_real_ip_from 103.21.244.0/22;\n\nreal_ip_header CF-Connecting-IP;\nreal_ip_recursive on;\n');
    });
    const guttedRun = spawnSync('bash', [driftAuditPath,
      '--receipt', receipt, '--root', gutted, '--unprivileged-root'], { encoding: 'utf8' });
    assert.notEqual(guttedRun.status, 0, 'drift audit accepted a truncated Cloudflare range list');
    assert.match(guttedRun.stderr, /range|cloudflare/i);

    // Losing the header directive silently disables real-IP resolution.
    const headerless = installFromReceipt(receiptData, join(base, 'root-headerless'), (root) => {
      const target = join(root, governed.target);
      writeFileSync(target, readFileSync(target, 'utf8')
        .replace('real_ip_header CF-Connecting-IP;', ''));
    });
    const headerlessRun = spawnSync('bash', [driftAuditPath,
      '--receipt', receipt, '--root', headerless, '--unprivileged-root'], { encoding: 'utf8' });
    assert.notEqual(headerlessRun.status, 0, 'drift audit accepted real-IP config with no header directive');

    // Stale beyond policy is drift even when the shape is perfect.
    const stale = installFromReceipt(receiptData, join(base, 'root-stale'), (root) => {
      const target = join(root, governed.target);
      const old = new Date(Date.now() - (lifecycle.staleness.fail_after_days + 30) * 86400000)
        .toISOString().slice(0, 10);
      writeFileSync(target, readFileSync(target, 'utf8')
        .replace(/# Regenerated \d{4}-\d{2}-\d{2}/, `# Regenerated ${old}`));
    });
    const staleRun = spawnSync('bash', [driftAuditPath,
      '--receipt', receipt, '--root', stale, '--unprivileged-root'], { encoding: 'utf8' });
    assert.notEqual(staleRun.status, 0, 'drift audit accepted real-IP data past its stale-data policy');
    assert.match(staleRun.stderr, /stale|old/i);
  } finally {
    discard(base);
  }
});

test('the real-IP exemption cannot smuggle arbitrary nginx configuration', () => {
  // Skipping byte equality must not become "anything goes". This snippet is
  // included into nginx server context, so an injected directive here is an
  // nginx directive on a live vhost, and lower-bound counts alone would let it
  // through while the audit kept reporting health.
  const base = mkdtempSync(join(tmpdir(), 'am2-cloudflare-injection-'));
  try {
    const lifecycle = JSON.parse(readFileSync(lifecyclePath, 'utf8'));
    const { receipt, receiptData } = sealedReceipt(base);
    const governed = receiptData.files.find((file) => file.id === lifecycle.host_security_file_id);
    const today = new Date().toISOString().slice(0, 10);

    const audit = (root) => spawnSync('bash', [driftAuditPath,
      '--receipt', receipt, '--root', root, '--unprivileged-root'], { encoding: 'utf8' });

    // An unrelated directive appended to otherwise genuine content.
    const injected = installFromReceipt(receiptData, join(base, 'root-injected'), (root) => {
      const target = join(root, governed.target);
      writeFileSync(target, readFileSync(target, 'utf8').replace(/# Regenerated \d{4}-\d{2}-\d{2}/, `# Regenerated ${today}`)
        + '\nlocation /admin { allow all; auth_basic off; }\n');
    });
    const injectedRun = audit(injected);
    assert.notEqual(injectedRun.status, 0, 'audit accepted an injected nginx directive');
    assert.match(injectedRun.stderr, /directive|unexpected|line/i);

    // Cloudflare's networks wholesale replaced by the attacker's, in the right
    // shape and quantity: this is what defeats every real-client-IP control.
    const substituted = installFromReceipt(receiptData, join(base, 'root-substituted'), (root) => {
      const v4 = Array.from({ length: 12 }, (_, i) => `set_real_ip_from 10.0.${i}.0/24;`).join('\n');
      const v6 = Array.from({ length: 6 }, (_, i) => `set_real_ip_from 2001:db8:${i}::/32;`).join('\n');
      writeFileSync(join(root, governed.target),
        `# Regenerated ${today}\n\n${v4}\n${v6}\n\nreal_ip_header CF-Connecting-IP;\nreal_ip_recursive on;\n`);
    });
    const substitutedRun = audit(substituted);
    assert.notEqual(substitutedRun.status, 0, 'audit accepted attacker networks as Cloudflare ranges');
    assert.match(substitutedRun.stderr, /cloudflare|network|range/i);

    // A genuine refresh that adds a range must still pass, or the whole point
    // of the separate lifecycle is lost.
    const refreshed = installFromReceipt(receiptData, join(base, 'root-refreshed'), (root) => {
      const target = join(root, governed.target);
      writeFileSync(target, readFileSync(target, 'utf8')
        .replace(/# Regenerated \d{4}-\d{2}-\d{2}/, `# Regenerated ${today}`)
        .replace('real_ip_header CF-Connecting-IP;', 'set_real_ip_from 199.27.128.0/21;\n\nreal_ip_header CF-Connecting-IP;'));
    });
    const refreshedRun = audit(refreshed);
    assert.equal(refreshedRun.status, 0,
      `a genuine Cloudflare refresh was rejected\n${refreshedRun.stdout}\n${refreshedRun.stderr}`);
  } finally {
    discard(base);
  }
});
