#!/usr/bin/env bash
set -euo pipefail

# Regenerate the list of peers nginx will let speak for someone else.
#
# Everything reaches this host through Cloudflare, so nginx's $remote_addr is a
# Cloudflare edge address and the visitor's own address arrives in
# CF-Connecting-IP. http_realip_module rewrites $remote_addr from that header --
# but only for peers inside the ranges below, which is the entire reason it is
# safe. A request that reaches the origin another way keeps its real peer
# address and cannot claim to be anyone.
#
# The ranges change. Hard-coding them once means that one day Cloudflare adds a
# range, nginx stops trusting it, and every address in the logs quietly becomes
# the edge again -- the exact failure this exists to end, arriving silently.
# So: fetch, sanity-check, write.
#
# Run it when Cloudflare announces a change, or on a timer. It is idempotent and
# prints whether anything moved.

out=${1:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)/nginx/am2-cloudflare-realip.conf}
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

fetch() {
    curl -fsS --max-time 20 "$1" || { echo "could not fetch $1" >&2; return 1; }
}

v4=$(fetch https://www.cloudflare.com/ips-v4)
v6=$(fetch https://www.cloudflare.com/ips-v6)

# A truncated or redirected response is the dangerous case: it would write a
# short list, nginx would stop trusting most of Cloudflare, and attribution
# would break without a single error. Cloudflare has published roughly 15 IPv4
# and 7 IPv6 ranges for years; refuse anything that looks nothing like that.
count_v4=$(printf '%s\n' "$v4" | grep -cE '^[0-9.]+/[0-9]+$' || true)
count_v6=$(printf '%s\n' "$v6" | grep -cE '^[0-9a-fA-F:]+/[0-9]+$' || true)
if (( count_v4 < 10 || count_v6 < 5 )); then
    echo "refusing to write: got $count_v4 IPv4 and $count_v6 IPv6 ranges, which is not a plausible list" >&2
    exit 1
fi

{
    echo "# Peers allowed to speak for someone else, via CF-Connecting-IP."
    echo "#"
    echo "# Generated by infra/scripts/refresh-cloudflare-ranges.sh -- do not hand-edit."
    echo "# Regenerated $(date -u +%Y-%m-%d) from cloudflare.com/ips-v4 and ips-v6."
    echo "#"
    echo "# Without this, \$remote_addr is a Cloudflare edge address and every log"
    echo "# line names the proxy instead of the visitor."
    echo
    printf '%s\n' "$v4" | grep -E '^[0-9.]+/[0-9]+$' | sed 's/^/set_real_ip_from /; s/$/;/'
    printf '%s\n' "$v6" | grep -E '^[0-9a-fA-F:]+/[0-9]+$' | sed 's/^/set_real_ip_from /; s/$/;/'
    echo
    echo "real_ip_header CF-Connecting-IP;"
    echo
    echo "# Cloudflare sends exactly one address in that header, so recursion has"
    echo "# nothing to walk -- but it is set on purpose rather than left to the"
    echo "# default, because the default changing is not something anybody would"
    echo "# notice here."
    echo "real_ip_recursive on;"
} > "$tmp"

if [[ -f $out ]] && diff -q <(grep -v '^# Regenerated' "$tmp") <(grep -v '^# Regenerated' "$out") >/dev/null; then
    echo "unchanged: $count_v4 IPv4 and $count_v6 IPv6 ranges"
else
    install -m 0644 "$tmp" "$out"
    echo "wrote $out: $count_v4 IPv4 and $count_v6 IPv6 ranges"
fi
